# Generated by Django 4.1 on 2022-09-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiantes',
            new_name='Estudiante',
        ),
    ]
