# Generated by Django 4.1 on 2022-09-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_estudianteb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('comentar', models.CharField(max_length=100)),
                ('EstudianteB', models.ManyToManyField(to='home.estudianteb')),
            ],
        ),
    ]
