# Generated by Django 4.1 on 2022-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=1000)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('EstudianteB', models.ManyToManyField(to='home.estudianteb')),
                ('art', models.ManyToManyField(to='home.art')),
            ],
        ),
    ]
